### PR TITLE
¯\_(ツ)_/¯

### PR DESCRIPTION
**Pull request by greggish**
Did i shot web right

### CODE REVIEW

**Comment by ajschumacher** [comment]
wait what? do you want me to merge and then open another pull request to the codefordc one? with a joke category? can't tell if serious... ¯_(ツ)_/¯

**Comment by greggish** [comment]
do those categories show up on a main page somewhere? it's not really a
joke, this is a very unpopular problem. but if it'd be polluting some page
to have that then I'll delete it.

**Comment by ajschumacher** [comment]
Probably best to not have the joke ship, I think. But this is a PR on my fork, so just take anything you do want and edit it into the codefordc/open211 and I'll close this right... now

**Comment by greggish** [comment]
ok thanks again, copied over sans snark.
resolving not to git on weekend evenings with drinks around.

**Pull request closed without merging**
